set_tests_properties(
    CryptoFileTest.RoundTripsEmptyAndChunkedFilesWithSeparatedKeys
    HasherDigest.MatchesKnownBlake3VectorForEmptyInput
    CryptoKeyDerivationTest.SeparatesEveryDomainAndKeysRemoteIdentifiers
    VaultTest.WritesObscuredBytesAndReadsExactKey
    WireIntegers.UsesObservableLittleEndianEncoding
    WireStrings.RoundTripsEmptyAsciiUtf8AndMaximumLengthStrings
    HistoryTest.BootstrapDeterminism
    HistoryTest.CanonicalTimestampRoundTripsWithoutChangingBytes
    TransactionCodecTest.RoundTripsAllActionsAndProgressFields
    TransactionCodecTest.UnicodeOperationPathsRoundTrip
    SyncCoordinatorTest.LogicalCheckpointCrashStatesRollbackWithoutPublicationOrLocalChange
    StateStorageDatabaseTest.FreshDatabaseCreatesInitialSchemaAndEmptyCache
    StateStorageDatabaseTest.UnicodePathRoundTrip
    PrivateStorageTest.CreatesRestrictedDirectoryAndFile
    H3LocalSyncTest.BootstrapAndNestedTreeConverge
    SnapshotValidationTest.RejectsNonPortableLogicalComponents
    ScannerTest.UnicodeFilenameRoundTrip
    PlatformPathTest.UnicodeRoundTripPreservesUtf8Bytes
    PlatformPathTest.UnicodeFilesystemOperationsAndAtomicReplacement
    ScannerTest.UnicodeSupplementaryPathsAndTargetedObservation
    RuntimeProfileTest.UnicodeFilesystemPathsSurvivePersistence
    H3LocalSyncTest.UnicodeSupplementaryAndExtendedSync
    PROPERTIES LABELS "release-critical"
)
