#include "core/history.hpp"

#include "core/wire.hpp"

#include <algorithm>
#include <array>
#include <bit>
#include <chrono>
#include <cstddef>
#include <cstring>
#include <filesystem>
#include <limits>
#include <map>
#include <new>
#include <optional>
#include <ratio>
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace kasumi::history {

namespace {

using Index = std::unordered_map<std::string, const LoadedCommit*>;
using PathSet = std::unordered_set<std::string>;

bool valid_tree_name(std::string_view name) noexcept {
    return valid_logical_path_component(name);
}

std::optional<std::filesystem::file_time_type>
file_time_from_system_nanos(std::int64_t nanos) noexcept {
    using FileDuration = std::filesystem::file_time_type::duration;
    using FileRep = FileDuration::rep;
    static_assert(std::is_integral_v<FileRep> && std::is_signed_v<FileRep>);
    static_assert(
        std::ratio_greater_equal_v<typename FileDuration::period, std::nano>);

    const auto delta = std::chrono::duration_cast<FileDuration>(
        std::chrono::nanoseconds{nanos});
    const auto origin = std::chrono::clock_cast<std::chrono::file_clock>(
                            std::chrono::system_clock::time_point{})
                            .time_since_epoch();
    if ((delta.count() > 0 &&
         origin.count() >
             std::numeric_limits<FileRep>::max() - delta.count()) ||
        (delta.count() < 0 &&
         origin.count() <
             std::numeric_limits<FileRep>::lowest() - delta.count())) {
        return std::nullopt;
    }
    return std::filesystem::file_time_type{
        FileDuration{origin.count() + delta.count()}};
}

template <typename Duration>
std::optional<std::int64_t>
duration_to_system_nanos(Duration duration) noexcept {
    using Rep = typename Duration::rep;
    using Factor = std::ratio_divide<typename Duration::period, std::nano>;
    static_assert(std::is_integral_v<Rep> && std::is_signed_v<Rep>);
    static_assert(Factor::num > 0 && Factor::den > 0);

    const auto value = static_cast<std::intmax_t>(duration.count());
    const bool negative = value < 0;
    const auto magnitude = negative
                               ? static_cast<std::uintmax_t>(-(value + 1)) + 1U
                               : static_cast<std::uintmax_t>(value);
    const auto numerator = static_cast<std::uintmax_t>(Factor::num);
    const auto denominator = static_cast<std::uintmax_t>(Factor::den);
    const auto whole = magnitude / denominator;
    const auto remainder = magnitude % denominator;
    if (whole > std::numeric_limits<std::uintmax_t>::max() / numerator) {
        return std::nullopt;
    }
    const auto whole_nanos = whole * numerator;
    if (remainder > std::numeric_limits<std::uintmax_t>::max() / numerator) {
        return std::nullopt;
    }
    const auto fractional_nanos = (remainder * numerator) / denominator;
    if (whole_nanos >
        std::numeric_limits<std::uintmax_t>::max() - fractional_nanos) {
        return std::nullopt;
    }
    const auto nanos = whole_nanos + fractional_nanos;
    constexpr auto positive_limit =
        static_cast<std::uintmax_t>(std::numeric_limits<std::int64_t>::max());
    constexpr auto negative_limit = positive_limit + 1U;
    if ((!negative && nanos > positive_limit) ||
        (negative && nanos > negative_limit)) {
        return std::nullopt;
    }
    if (negative) {
        if (nanos == negative_limit) {
            return std::numeric_limits<std::int64_t>::lowest();
        }
        return -static_cast<std::int64_t>(nanos);
    }
    return static_cast<std::int64_t>(nanos);
}

std::optional<std::int64_t>
system_nanos_from_file_time(std::filesystem::file_time_type value) noexcept {
    // Directories generated by merge or default-initialized nodes deliberately
    // have no observed mtime. Their canonical wire representation is zero
    // (Unix/system epoch), independent of the file_clock epoch.
    if (value == std::filesystem::file_time_type{}) {
        return std::int64_t{0};
    }
    using FileDuration = std::filesystem::file_time_type::duration;
    const auto origin = std::chrono::clock_cast<std::chrono::file_clock>(
                            std::chrono::system_clock::time_point{})
                            .time_since_epoch();
    const auto delta_count = value.time_since_epoch().count() - origin.count();
    return duration_to_system_nanos(FileDuration{delta_count});
}

std::vector<std::uint8_t> serialize_tree(const Snapshot& snapshot,
                                         std::uint64_t height) {
    wire::Writer writer;
    writer.buffer.reserve(1024 * 1024);

    const char magic[] = "KASU";
    wire::write_bytes(writer, std::as_bytes(std::span{magic, 4}));
    wire::write<std::uint64_t>(writer, height);

    struct OpenDirectory {
        std::size_t row;
        std::size_t count_offset;
        std::uint32_t children;
    };
    std::vector<OpenDirectory> directories;

    const auto close = [&] {
        const auto directory = directories.back();
        auto children = directory.children;
        if constexpr (std::endian::native != std::endian::little) {
            children = std::byteswap(children);
        }
        std::memcpy(writer.buffer.data() + directory.count_offset,
                    &children,
                    sizeof(children));
        directories.pop_back();
    };

    for (std::size_t index = 0; index < snapshot.rows.size(); ++index) {
        const auto& row = snapshot.rows[index];
        while (!directories.empty() &&
               row_parent(row.path) !=
                   snapshot.rows[directories.back().row].path) {
            close();
        }
        if (!directories.empty()) {
            ++directories.back().children;
        }

        wire::write_string(writer, row_name(row.path));
        wire::write_array(writer, row.hash);
        wire::write<std::uint64_t>(writer, row.size);
        const auto nanos = system_nanos_from_file_time(row.mtime);
        if (!nanos) {
            throw std::runtime_error("tree timestamp is out of range");
        }
        wire::write<std::int64_t>(writer, *nanos);
        wire::write<std::uint8_t>(writer,
                                  static_cast<std::uint8_t>(row.is_directory));

        const auto count_offset = writer.buffer.size();
        wire::write<std::uint32_t>(writer, 0U);
        if (row.is_directory) {
            directories.push_back({index, count_offset, 0U});
        }
    }
    while (!directories.empty()) {
        close();
    }

    std::vector<std::uint8_t> result(writer.buffer.size());
    std::memcpy(result.data(), writer.buffer.data(), writer.buffer.size());
    return result;
}

Snapshot deserialize_tree(const std::vector<std::uint8_t>& bytes,
                          std::uint64_t& height) {
    if (bytes.size() < 4 ||
        !std::equal(bytes.begin(), bytes.begin() + 4, "KASU")) {
        throw std::runtime_error("invalid tree encoding");
    }

    std::span<const std::byte> data(
        reinterpret_cast<const std::byte*>(bytes.data()), bytes.size());
    wire::Reader reader{data.subspan(4)};
    auto decoded_height = wire::read<std::uint64_t>(reader);
    if (!decoded_height) {
        throw std::runtime_error("truncated tree root");
    }
    height = *decoded_height;

    struct Pending {
        std::string path;
        std::uint32_t remaining;
        std::uint32_t depth;
    };
    std::uint32_t root_children = 0;
    Snapshot snapshot;

    auto read_row = [&reader](std::string path,
                              std::uint32_t& child_count) -> NodeRow {
        auto hash = wire::read_array<32>(reader);
        if (!hash) {
            throw std::runtime_error("truncated tree row");
        }
        NodeRow row{.path = std::move(path), .hash = *hash};
        auto size = wire::read<std::uint64_t>(reader);
        auto nanos = wire::read<std::int64_t>(reader);
        auto is_directory = wire::read<std::uint8_t>(reader);
        auto children = wire::read<std::uint32_t>(reader);
        if (!size || !nanos || !is_directory || !children) {
            throw std::runtime_error("truncated tree row");
        }
        row.size = *size;
        if (*is_directory > 1) {
            throw std::runtime_error("invalid tree node type");
        }
        const auto mtime =
            (*nanos == 0)
                ? std::optional<
                      std::filesystem::file_time_type>{std::filesystem::
                                                           file_time_type{}}
                : file_time_from_system_nanos(*nanos);
        if (!mtime) {
            throw std::runtime_error("tree timestamp is out of range");
        }
        row.mtime = *mtime;
        row.is_directory = *is_directory == 1;
        child_count = *children;
        if (static_cast<std::uint64_t>(child_count) * 29ULL >
            reader.data.size()) {
            throw std::runtime_error("forged tree child count");
        }
        if (!row.is_directory && child_count != 0) {
            throw std::runtime_error("file has tree children");
        }
        return row;
    };

    auto root_name = wire::read_string(reader);
    if (!root_name || !root_name->empty()) {
        throw std::runtime_error("invalid tree root name");
    }
    auto root = read_row("", root_children);
    if (!root.is_directory) {
        throw std::runtime_error("tree root is not a directory");
    }
    snapshot.rows.push_back(std::move(root));

    std::vector<Pending> stack;
    if (root_children) {
        stack.push_back({"", root_children, 0});
    }
    while (!stack.empty()) {
        auto& parent = stack.back();
        auto name = wire::read_string(reader);
        if (!name || !valid_tree_name(*name)) {
            throw std::runtime_error("invalid tree path component");
        }
        const auto path =
            parent.path.empty() ? *name : parent.path + '/' + *name;
        const auto depth = parent.depth + 1;
        if (depth > 256) {
            throw std::runtime_error("tree depth exceeds limit");
        }
        if (--parent.remaining == 0) {
            stack.pop_back();
        }
        std::uint32_t children = 0;
        snapshot.rows.push_back(read_row(path, children));
        if (children) {
            stack.push_back({path, children, depth});
        }
    }

    if (!reader.data.empty()) {
        throw std::runtime_error("trailing tree bytes");
    }
    std::ranges::sort(snapshot.rows, path_less, &NodeRow::path);
    const auto duplicate = std::ranges::adjacent_find(
        snapshot.rows, [](const NodeRow& left, const NodeRow& right) {
            return left.path == right.path;
        });
    if (duplicate != snapshot.rows.end()) {
        throw std::runtime_error("duplicate tree path");
    }
    return snapshot;
}

std::vector<std::string> ancestors_of(std::string_view path) {
    std::vector<std::string> result;
    while (!path.empty()) {
        const auto separator = path.rfind('/');
        path = separator == std::string_view::npos ? std::string_view{}
                                                   : path.substr(0, separator);
        result.emplace_back(path);
    }
    return result;
}

bool same_state(const NodeRow* left, const NodeRow* right) {
    if (!left && !right) {
        return true;
    }
    if (!left || !right || left->is_directory != right->is_directory) {
        return false;
    }
    return left->is_directory ||
           (left->hash == right->hash && left->size == right->size);
}

std::expected<void, Error>
validate_snapshot_structure(const Snapshot& snapshot) {
    if (!valid_snapshot(snapshot, false)) {
        return std::unexpected(
            Error{ErrorCode::InvalidSnapshot, "invalid snapshot"});
    }
    return {};
}

std::expected<void, Error> validate_dag(const Index& index) {
    enum class Color {
        White,
        Gray,
        Black
    };
    struct Frame {
        std::string id;
        std::size_t next_parent = 0;
        std::size_t depth = 0;
    };

    std::unordered_map<std::string, Color> colors;
    for (const auto& [id, commit] : index) {
        static_cast<void>(commit);
        colors.emplace(id, Color::White);
    }

    for (const auto& [root, unused] : index) {
        static_cast<void>(unused);
        if (colors.at(root) != Color::White) {
            continue;
        }

        std::vector<Frame> stack{{root, 0, 0}};
        while (!stack.empty()) {
            auto& frame = stack.back();
            if (frame.depth > maximum_graph_depth) {
                return std::unexpected(
                    Error{ErrorCode::LimitExceeded,
                          "profundidade máxima do grafo excedida"});
            }
            colors.at(frame.id) = Color::Gray;
            const auto& parents = index.at(frame.id)->commit.parents;
            if (frame.next_parent == parents.size()) {
                colors.at(frame.id) = Color::Black;
                stack.pop_back();
                continue;
            }

            const auto& parent = parents[frame.next_parent++];
            if (index.at(parent)->commit.created_at >
                index.at(frame.id)->commit.created_at) {
                return std::unexpected(
                    Error{ErrorCode::InvalidCommit,
                          "regressão de timestamp detectada"});
            }
            switch (colors.at(parent)) {
                case Color::Gray:
                    return std::unexpected(
                        Error{ErrorCode::Cycle, "ciclo detectado no grafo"});
                case Color::Black:
                    break;
                case Color::White:
                    stack.push_back({parent, 0, frame.depth + 1});
                    break;
            }
        }
    }
    return {};
}

std::expected<std::unordered_set<std::string>, Error>
collect_ancestors(const Index& index, const std::string& head) {
    std::unordered_set<std::string> result;
    std::vector<std::pair<std::string, std::size_t>> stack{{head, 0}};
    while (!stack.empty()) {
        auto [id, depth] = std::move(stack.back());
        stack.pop_back();
        if (depth > maximum_graph_depth) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "graph depth exceeded"});
        }
        if (!result.insert(id).second) {
            continue;
        }
        if (result.size() > maximum_loaded_commit_count) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "ancestor count exceeded"});
        }
        for (const auto& parent : index.at(id)->commit.parents) {
            stack.emplace_back(parent, depth + 1);
        }
    }
    return result;
}

struct HeadChanges {
    std::string head_id;
    const Snapshot* tree = nullptr;
    PathSet directly_changed;
    PathSet changed_subtrees;
};

HeadChanges build_head_changes(const Snapshot& base,
                               const std::string& head_id,
                               const Snapshot& head) {
    HeadChanges changes{.head_id = head_id,
                        .tree = &head,
                        .directly_changed = {},
                        .changed_subtrees = {}};
    std::set<std::string> paths;
    for (const auto& row : base.rows) {
        paths.insert(row.path);
    }
    for (const auto& row : head.rows) {
        paths.insert(row.path);
    }

    for (const auto& path : paths) {
        const auto* base_row = find_row(base, path);
        const auto* head_row = find_row(head, path);
        if (same_state(base_row, head_row)) {
            continue;
        }
        changes.directly_changed.insert(path);
        for (const auto& ancestor : ancestors_of(path)) {
            changes.changed_subtrees.insert(ancestor);
        }
    }
    return changes;
}

bool conflict_path_is_safe(std::string_view candidate,
                           const std::map<std::string, bool>& reserved) {
    const auto key_candidate = portable_case_key(candidate);
    for (const auto& [path, is_directory] : reserved) {
        const auto key_path = portable_case_key(path);
        if (key_path == key_candidate ||
            is_descendant(key_path, key_candidate) ||
            (!is_directory && is_descendant(key_candidate, key_path))) {
            return false;
        }
    }
    return true;
}

std::expected<std::string, Error>
select_conflict_path(std::string_view path,
                     std::string_view source_head_id,
                     std::map<std::string, bool>& reserved) {
    const std::string suffix_base =
        ".kasumiconflict_" + std::string(source_head_id.substr(0, 12));
    for (std::size_t suffix = 0;; ++suffix) {
        std::string suffix_str = suffix_base;
        if (suffix != 0) {
            suffix_str += '.' + std::to_string(suffix);
        }
        std::string candidate = make_conflict_path(path, suffix_str);
        if (conflict_path_is_safe(candidate, reserved)) {
            reserved.emplace(candidate, false);
            return candidate;
        }
        if (suffix == std::numeric_limits<std::size_t>::max()) {
            return std::unexpected(Error{ErrorCode::UnsafeMerge,
                                         "cannot find safe conflict path"});
        }
    }
}

std::expected<Snapshot, Error>
merge_snapshots(const Snapshot& base,
                const std::vector<HeadChanges>& heads,
                bool& has_conflicts) {
    enum class VariantKind {
        Absent,
        File,
        Directory
    };
    struct Variant {
        VariantKind kind = VariantKind::Absent;
        std::optional<NodeRow> row;
        std::string source_head_id;
    };

    std::set<std::string> all_paths;
    std::map<std::string, bool> reserved;
    for (const auto& row : base.rows) {
        all_paths.insert(row.path);
        reserved.emplace(row.path, row.is_directory);
    }
    for (const auto& head : heads) {
        for (const auto& row : head.tree->rows) {
            all_paths.insert(row.path);
            reserved.emplace(row.path, row.is_directory);
        }
    }

    std::vector<NodeRow> final_rows;
    for (const auto& path : all_paths) {
        const auto* base_row = find_row(base, path);
        std::vector<Variant> variants;

        for (const auto& head : heads) {
            const auto* head_row = find_row(*head.tree, path);
            const bool active = head.directly_changed.contains(path) ||
                                (head_row && head_row->is_directory &&
                                 head.changed_subtrees.contains(path));
            if (!active) {
                continue;
            }

            auto existing =
                std::ranges::find_if(variants, [&](const Variant& variant) {
                    return same_state(variant.row ? &*variant.row : nullptr,
                                      head_row);
                });
            if (existing != variants.end()) {
                if (head_row && !head_row->is_directory && existing->row &&
                    head_row->mtime > existing->row->mtime) {
                    existing->row->mtime = head_row->mtime;
                }
                if (head.head_id < existing->source_head_id) {
                    existing->source_head_id = head.head_id;
                }
                continue;
            }

            variants.push_back(Variant{
                .kind = !head_row                ? VariantKind::Absent
                        : head_row->is_directory ? VariantKind::Directory
                                                 : VariantKind::File,
                .row = head_row ? std::make_optional(*head_row) : std::nullopt,
                .source_head_id = head.head_id});
        }

        if (variants.empty()) {
            if (base_row) {
                final_rows.push_back(*base_row);
            }
            continue;
        }
        if (variants.size() == 1) {
            if (variants.front().row) {
                final_rows.push_back(*variants.front().row);
            }
            continue;
        }

        has_conflicts = true;
        const auto rank = [](VariantKind kind) {
            switch (kind) {
                case VariantKind::Directory:
                    return 0;
                case VariantKind::File:
                    return 1;
                case VariantKind::Absent:
                    return 2;
            }
            return 3;
        };
        std::ranges::sort(variants,
                          [&](const Variant& left, const Variant& right) {
                              if (rank(left.kind) != rank(right.kind)) {
                                  return rank(left.kind) < rank(right.kind);
                              }
                              return left.source_head_id < right.source_head_id;
                          });

        if (variants.front().row) {
            final_rows.push_back(*variants.front().row);
        }
        for (std::size_t i = 1; i < variants.size(); ++i) {
            if (!variants[i].row) {
                continue;
            }
            auto conflict_path = select_conflict_path(
                path, variants[i].source_head_id, reserved);
            if (!conflict_path) {
                return std::unexpected(conflict_path.error());
            }
            auto conflict_row = *variants[i].row;
            conflict_row.path = *conflict_path;
            final_rows.push_back(std::move(conflict_row));
        }
    }

    std::unordered_set<std::string> final_paths;
    std::unordered_set<std::string> final_directories;
    for (const auto& row : final_rows) {
        if (!final_paths.insert(row.path).second) {
            return std::unexpected(
                Error{ErrorCode::UnsafeMerge, "duplicate path in merge"});
        }
        if (row.is_directory) {
            final_directories.insert(row.path);
        }
    }

    std::vector<NodeRow> synthesized_parents;
    for (const auto& row : final_rows) {
        for (const auto& ancestor : ancestors_of(row.path)) {
            if (final_paths.contains(ancestor)) {
                if (!final_directories.contains(ancestor)) {
                    return std::unexpected(
                        Error{ErrorCode::UnsafeMerge, "ancestor is a file"});
                }
                continue;
            }
            final_paths.insert(ancestor);
            final_directories.insert(ancestor);
            synthesized_parents.push_back(NodeRow{.path = ancestor,
                                                  .hash = {},
                                                  .size = 0,
                                                  .mtime = {},
                                                  .is_directory = true});
        }
    }
    final_rows.insert(final_rows.end(),
                      synthesized_parents.begin(),
                      synthesized_parents.end());

    if (!final_paths.contains("")) {
        final_rows.push_back(NodeRow{.path = "",
                                     .hash = {},
                                     .size = 0,
                                     .mtime = {},
                                     .is_directory = true});
    } else if (!final_directories.contains("")) {
        return std::unexpected(
            Error{ErrorCode::UnsafeMerge, "root is not a directory"});
    }

    for (auto& row : final_rows) {
        if (row.is_directory) {
            row.hash = {};
            row.size = 0;
            row.mtime = {};
        }
    }

    Snapshot merged{.rows = std::move(final_rows)};
    finalize_snapshot(merged);
    return merged;
}

} // namespace

bool valid_commit_id(std::string_view id) noexcept {
    if (id.size() != 64) {
        return false;
    }
    for (const char c : id) {
        if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'))) {
            return false;
        }
    }
    return true;
}

CommitResult make_commit(std::uint64_t height,
                         std::vector<std::string> parents,
                         Snapshot tree,
                         std::int64_t created_at) {
    try {
        if (parents.size() > maximum_parent_count) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "too many parents"});
        }
        for (const auto& parent : parents) {
            if (!valid_commit_id(parent)) {
                return std::unexpected(
                    Error{ErrorCode::InvalidParent, "invalid parent id"});
            }
        }
        std::ranges::sort(parents);
        if (std::ranges::adjacent_find(parents) != parents.end()) {
            return std::unexpected(
                Error{ErrorCode::InvalidParent, "duplicate parent"});
        }
        auto valid = validate_snapshot_structure(tree);
        if (!valid) {
            return std::unexpected(valid.error());
        }
        return Commit{.height = height,
                      .created_at = created_at,
                      .parents = std::move(parents),
                      .tree = std::move(tree)};
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "allocation failed"});
    } catch (...) {
        return std::unexpected(
            Error{ErrorCode::InvalidCommit, "exception in make_commit"});
    }
}

CommitResult
make_bootstrap(Snapshot tree, std::uint64_t height, std::int64_t created_at) {
    return make_commit(height, {}, std::move(tree), created_at);
}

CommitResult make_empty_bootstrap(std::int64_t created_at) {
    try {
        Snapshot tree{.rows = {NodeRow{.path = "",
                                       .hash = {},
                                       .size = 0,
                                       .mtime = {},
                                       .is_directory = true}}};
        finalize_snapshot(tree);
        return make_bootstrap(std::move(tree), 0, created_at);
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "allocation failed"});
    } catch (...) {
        return std::unexpected(Error{ErrorCode::InvalidCommit,
                                     "exception in make_empty_bootstrap"});
    }
}

BytesResult serialize(const Commit& commit) {
    try {
        auto valid = validate_snapshot_structure(commit.tree);
        if (!valid) {
            return std::unexpected(valid.error());
        }
        if (commit.parents.size() > maximum_parent_count) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "too many parents"});
        }

        std::string previous;
        for (const auto& parent : commit.parents) {
            if (!valid_commit_id(parent)) {
                return std::unexpected(
                    Error{ErrorCode::InvalidParent, "invalid parent id"});
            }
            if (!previous.empty() && parent <= previous) {
                return std::unexpected(
                    Error{ErrorCode::InvalidParent,
                          "parents not sorted or duplicate"});
            }
            previous = parent;
        }

        std::vector<uint8_t> tree_bytes;
        try {
            tree_bytes = serialize_tree(commit.tree, commit.height);
        } catch (const std::exception& e) {
            return std::unexpected(Error{
                ErrorCode::InvalidEncoding,
                std::string("falha na serialização da árvore: ") + e.what()});
        } catch (...) {
            return std::unexpected(Error{ErrorCode::InvalidEncoding,
                                         "falha na serialização da árvore"});
        }
        if (tree_bytes.size() > maximum_commit_plaintext_size) {
            return std::unexpected(Error{ErrorCode::LimitExceeded,
                                         "tree size exceeds maximum size"});
        }

        wire::Writer writer;
        wire::write_array(writer,
                          std::array<std::byte, 4>{std::byte{'K'},
                                                   std::byte{'C'},
                                                   std::byte{'O'},
                                                   std::byte{'M'}});
        wire::write(writer, static_cast<uint8_t>(2));
        wire::write(writer, static_cast<uint64_t>(commit.height));
        wire::write<int64_t>(writer, commit.created_at);
        wire::write(writer, static_cast<uint32_t>(commit.parents.size()));
        for (const auto& parent : commit.parents) {
            auto hash = hash_from_hex(parent);
            if (!hash) {
                return std::unexpected(
                    Error{ErrorCode::InvalidParent, "invalid parent hex"});
            }
            std::array<std::byte, 32> parent_bytes;
            for (std::size_t i = 0; i < parent_bytes.size(); ++i) {
                parent_bytes[i] = (*hash)[i];
            }
            wire::write_array(writer, parent_bytes);
        }
        wire::write(writer, static_cast<uint64_t>(tree_bytes.size()));
        wire::write_bytes(writer, std::as_bytes(std::span{tree_bytes}));
        if (writer.buffer.size() > maximum_commit_plaintext_size) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "commit exceeds maximum size"});
        }

        std::vector<uint8_t> result(writer.buffer.size());
        for (std::size_t i = 0; i < writer.buffer.size(); ++i) {
            result[i] = static_cast<uint8_t>(writer.buffer[i]);
        }
        return result;
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "allocation failed"});
    } catch (...) {
        return std::unexpected(
            Error{ErrorCode::InvalidEncoding, "exception in serialize"});
    }
}

CommitResult deserialize(std::span<const std::uint8_t> bytes) {
    if (bytes.size() > maximum_commit_plaintext_size) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "commit exceeds maximum size"});
    }
    try {
        std::span<const std::byte> data(
            reinterpret_cast<const std::byte*>(bytes.data()), bytes.size());
        wire::Reader reader{data};
        auto magic = wire::read_array<4>(reader);
        if (!magic)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated magic"});
        if ((*magic)[0] != std::byte{'K'} || (*magic)[1] != std::byte{'C'} ||
            (*magic)[2] != std::byte{'O'} || (*magic)[3] != std::byte{'M'}) {
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "invalid magic"});
        }
        auto version = wire::read<uint8_t>(reader);
        if (!version)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated version"});
        if (*version != 2)
            return std::unexpected(
                Error{ErrorCode::UnsupportedVersion, "unsupported version"});
        auto height = wire::read<uint64_t>(reader);
        if (!height)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated height"});
        auto created_at = wire::read<int64_t>(reader);
        if (!created_at)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated created_at"});
        auto parent_count = wire::read<uint32_t>(reader);
        if (!parent_count)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated parent count"});
        if (*parent_count > maximum_parent_count)
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "too many parents"});

        std::vector<std::string> parents;
        std::string previous;
        for (uint32_t i = 0; i < *parent_count; ++i) {
            auto parent_bytes = wire::read_array<32>(reader);
            if (!parent_bytes)
                return std::unexpected(
                    Error{ErrorCode::InvalidEncoding, "truncated parent"});
            Hash hash;
            for (std::size_t j = 0; j < hash.size(); ++j)
                hash[j] = (*parent_bytes)[j];
            auto parent = hash_hex(hash);
            if (!previous.empty() && parent <= previous)
                return std::unexpected(
                    Error{ErrorCode::InvalidParent,
                          "parents not strictly increasing"});
            parents.push_back(parent);
            previous = std::move(parent);
        }

        auto tree_size = wire::read<uint64_t>(reader);
        if (!tree_size)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated tree size"});
        if (*tree_size > maximum_commit_plaintext_size) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "tree size exceeds limits"});
        }
        auto tree_bytes =
            wire::read_bytes(reader, static_cast<std::size_t>(*tree_size));
        if (!tree_bytes)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "truncated tree"});
        if (!reader.data.empty())
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding, "trailing bytes"});

        std::vector<uint8_t> tree_vector(tree_bytes->size());
        for (std::size_t i = 0; i < tree_bytes->size(); ++i)
            tree_vector[i] = static_cast<uint8_t>((*tree_bytes)[i]);
        uint64_t generation = 0;
        Snapshot tree;
        try {
            tree = deserialize_tree(tree_vector, generation);
        } catch (...) {
            return std::unexpected(Error{ErrorCode::InvalidEncoding,
                                         "tree deserialization failed"});
        }
        if (generation != *height)
            return std::unexpected(
                Error{ErrorCode::InvalidEncoding,
                      "tree height does not match commit height"});
        auto valid = validate_snapshot_structure(tree);
        if (!valid)
            return std::unexpected(valid.error());
        return Commit{.height = *height,
                      .created_at = *created_at,
                      .parents = std::move(parents),
                      .tree = std::move(tree)};
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "allocation failed"});
    } catch (...) {
        return std::unexpected(
            Error{ErrorCode::InvalidEncoding, "exception in deserialize"});
    }
}

StringResult compute_id(std::span<const std::uint8_t> canonical_bytes) {
    try {
        if (canonical_bytes.size() > maximum_commit_plaintext_size) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "commit exceeds maximum size"});
        }
        return hash_hex(kasumi::hasher::hash_bytes(canonical_bytes.data(),
                                                   canonical_bytes.size()));
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "allocation failed"});
    } catch (...) {
        return std::unexpected(
            Error{ErrorCode::InvalidEncoding, "exception in compute_id"});
    }
}

StringResult compute_id(const Commit& commit) {
    try {
        auto bytes = serialize(commit);
        if (!bytes)
            return std::unexpected(bytes.error());
        return compute_id(*bytes);
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "allocation failed"});
    } catch (...) {
        return std::unexpected(
            Error{ErrorCode::InvalidEncoding, "exception in compute_id"});
    }
}

static ResolutionResult
resolve_impl(std::span<const LoadedCommit> commits,
             std::span<const std::string> marked_heads,
             std::span<const std::string> trusted_anchor_ids,
             bool identifiers_authenticated) {
    try {
        if (commits.size() > maximum_loaded_commit_count) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "limite de commits excedido"});
        }
        if (marked_heads.empty()) {
            return std::unexpected(
                Error{ErrorCode::InvalidHead, "lista de heads marcadas vazia"});
        }
        if (marked_heads.size() > maximum_marked_head_count) {
            return std::unexpected(
                Error{ErrorCode::LimitExceeded, "muitas heads marcadas"});
        }

        std::vector<std::string> unique_heads(marked_heads.begin(),
                                              marked_heads.end());
        std::ranges::sort(unique_heads);
        unique_heads.erase(std::ranges::unique(unique_heads).begin(),
                           unique_heads.end());
        for (const auto& head : unique_heads) {
            if (!valid_commit_id(head))
                return std::unexpected(Error{ErrorCode::InvalidHead,
                                             "identificador de head inválido"});
        }

        std::unordered_set<std::string> trusted_anchors;
        for (const auto& trusted_anchor_id : trusted_anchor_ids) {
            if (!valid_commit_id(trusted_anchor_id) ||
                !trusted_anchors.insert(trusted_anchor_id).second) {
                return std::unexpected(Error{ErrorCode::InvalidCommitId,
                                             "fronteira confiável inválida"});
            }
        }

        Index index;
        std::size_t found_trusted_anchors = 0;
        for (const auto& loaded : commits) {
            if (!index.emplace(loaded.id, &loaded).second) {
                return std::unexpected(Error{ErrorCode::DuplicateCommit,
                                             "commit duplicado na entrada"});
            }
            auto valid = validate_snapshot_structure(loaded.commit.tree);
            if (!valid)
                return std::unexpected(valid.error());
            if (trusted_anchors.contains(loaded.id)) {
                if (!loaded.commit.parents.empty()) {
                    return std::unexpected(Error{
                        ErrorCode::InvalidParent,
                        "a âncora confiável deve encerrar o grafo carregado"});
                }
                ++found_trusted_anchors;
            } else if (!identifiers_authenticated) {
                auto computed = compute_id(loaded.commit);
                if (!computed)
                    return std::unexpected(computed.error());
                if (*computed != loaded.id)
                    return std::unexpected(
                        Error{ErrorCode::InvalidCommitId,
                              "o id não corresponde ao conteúdo do commit"});
            }
        }
        if (found_trusted_anchors != trusted_anchors.size()) {
            return std::unexpected(
                Error{ErrorCode::MissingParent, "fronteira confiável ausente"});
        }
        for (const auto& head : unique_heads) {
            if (!index.contains(head))
                return std::unexpected(
                    Error{ErrorCode::InvalidHead,
                          "head não encontrada nos commits carregados"});
        }

        for (const auto& [id, loaded] : index) {
            if (loaded->commit.parents.size() > maximum_parent_count) {
                return std::unexpected(
                    Error{ErrorCode::LimitExceeded, "muitos pais no commit"});
            }
            if (loaded->commit.parents.empty())
                continue;
            std::uint64_t max_parent_height = 0;
            for (const auto& parent : loaded->commit.parents) {
                const auto it = index.find(parent);
                if (it == index.end())
                    return std::unexpected(
                        Error{ErrorCode::MissingParent,
                              "pai não encontrado nos commits carregados"});
                max_parent_height =
                    std::max(max_parent_height, it->second->commit.height);
            }
            if (max_parent_height ==
                std::numeric_limits<std::uint64_t>::max()) {
                return std::unexpected(
                    Error{ErrorCode::HeightMismatch,
                          "altura do pai transborda a altura do commit"});
            }
            if (loaded->commit.height != max_parent_height + 1) {
                return std::unexpected(
                    Error{ErrorCode::HeightMismatch,
                          "a altura não corresponde a max(pais) + 1"});
            }
            static_cast<void>(id);
        }
        auto dag_valid = validate_dag(index);
        if (!dag_valid)
            return std::unexpected(dag_valid.error());

        std::unordered_map<std::string, std::unordered_set<std::string>>
            ancestor_sets;
        for (const auto& head : unique_heads) {
            auto ancestors = collect_ancestors(index, head);
            if (!ancestors)
                return std::unexpected(ancestors.error());
            ancestor_sets.emplace(head, std::move(*ancestors));
        }

        std::vector<std::string> logical_heads;
        for (const auto& head : unique_heads) {
            bool stale = false;
            for (const auto& other : unique_heads) {
                if (head != other && ancestor_sets.at(other).contains(head)) {
                    stale = true;
                    break;
                }
            }
            if (!stale)
                logical_heads.push_back(head);
        }

        if (logical_heads.size() > maximum_parent_count)
            return std::unexpected(
                Error{ErrorCode::LimitExceeded,
                      "muitas heads lógicas para um único commit de merge "
                      "(limite de pais excedido)"});

        if (logical_heads.size() == 1) {
            const auto& head = logical_heads.front();
            return Resolution{.tree = index.at(head)->commit.tree,
                              .height = index.at(head)->commit.height,
                              .heads = {head},
                              .has_conflicts = false};
        }

        std::unordered_set<std::string> common_ancestors =
            ancestor_sets.at(logical_heads.front());
        for (std::size_t i = 1; i < logical_heads.size(); ++i) {
            const auto& ancestors = ancestor_sets.at(logical_heads[i]);
            for (auto it = common_ancestors.begin();
                 it != common_ancestors.end();) {
                if (!ancestors.contains(*it))
                    it = common_ancestors.erase(it);
                else
                    ++it;
            }
        }
        if (common_ancestors.empty())
            return std::unexpected(Error{ErrorCode::NoCommonAncestor,
                                         "nenhum ancestral comum encontrado"});

        std::uint64_t max_height = 0;
        for (const auto& ancestor : common_ancestors) {
            max_height =
                std::max(max_height, index.at(ancestor)->commit.height);
        }
        std::vector<std::string> merge_bases;
        for (const auto& ancestor : common_ancestors) {
            if (index.at(ancestor)->commit.height == max_height)
                merge_bases.push_back(ancestor);
        }
        if (merge_bases.size() > 1)
            return std::unexpected(Error{
                ErrorCode::AmbiguousMergeBase,
                "base de merge ambígua (criss-cross / ambiguous merge base)"});

        const auto& base = index.at(merge_bases.front())->commit.tree;
        std::vector<HeadChanges> changes;
        changes.reserve(logical_heads.size());
        for (const auto& head : logical_heads) {
            changes.push_back(
                build_head_changes(base, head, index.at(head)->commit.tree));
        }

        bool has_conflicts = false;
        auto merged = merge_snapshots(base, changes, has_conflicts);
        if (!merged)
            return std::unexpected(merged.error());
        auto valid = validate_snapshot_structure(*merged);
        if (!valid)
            return std::unexpected(
                Error{ErrorCode::UnsafeMerge, valid.error().detail});

        std::uint64_t height = 0;
        for (const auto& head : logical_heads)
            height = std::max(height, index.at(head)->commit.height);
        return Resolution{.tree = std::move(*merged),
                          .height = height,
                          .heads = std::move(logical_heads),
                          .has_conflicts = has_conflicts};
    } catch (const std::bad_alloc&) {
        return std::unexpected(
            Error{ErrorCode::LimitExceeded, "falha de alocação de memória"});
    } catch (...) {
        return std::unexpected(Error{ErrorCode::InvalidCommit,
                                     "exceção durante resolução de histórico"});
    }
}

ResolutionResult resolve(std::span<const LoadedCommit> commits,
                         std::span<const std::string> marked_heads) {
    return resolve_impl(commits, marked_heads, {}, false);
}

ResolutionResult
resolve_authenticated(std::span<const LoadedCommit> commits,
                      std::span<const std::string> marked_heads) {
    return resolve_impl(commits, marked_heads, {}, true);
}

ResolutionResult resolve_from_anchor(std::span<const LoadedCommit> commits,
                                     std::span<const std::string> marked_heads,
                                     std::string_view trusted_anchor_id) {
    if (trusted_anchor_id.empty()) {
        return std::unexpected(
            Error{ErrorCode::InvalidCommitId, "trusted anchor is empty"});
    }
    const std::array anchors{std::string{trusted_anchor_id}};
    return resolve_impl(commits, marked_heads, anchors, false);
}

ResolutionResult
resolve_from_anchor_authenticated(std::span<const LoadedCommit> commits,
                                  std::span<const std::string> marked_heads,
                                  std::string_view trusted_anchor_id) {
    if (trusted_anchor_id.empty()) {
        return std::unexpected(
            Error{ErrorCode::InvalidCommitId, "trusted anchor is empty"});
    }
    const std::array anchors{std::string{trusted_anchor_id}};
    return resolve_impl(commits, marked_heads, anchors, true);
}

ResolutionResult resolve_from_frontier_authenticated(
    std::span<const LoadedCommit> commits,
    std::span<const std::string> marked_heads,
    std::span<const std::string> trusted_anchor_ids) {
    if (trusted_anchor_ids.empty()) {
        return std::unexpected(
            Error{ErrorCode::InvalidCommitId, "trusted frontier is empty"});
    }
    return resolve_impl(commits, marked_heads, trusted_anchor_ids, true);
}

} // namespace kasumi::history
