#!/usr/bin/env python3
"""
Generates generated/cli/i18n_embedded.hpp with bounded string literal fragments.
Splits embedded catalogs so that no individual string literal exceeds the MSVC C2026 limit.
"""

import argparse
import re
import sys
from pathlib import Path

MAX_RAW_DELIMITER_LENGTH = 16
RAW_DELIMITER_OCCURRENCE = re.compile(r'\)(kasumi(?:_[0-9]+)?)"')


def chunk_by_bytes(text: str, max_bytes: int = 2048) -> list[str]:
    lines = text.splitlines(keepends=True)
    chunks = []
    current_chunk = []
    current_bytes = 0
    for line in lines:
        line_bytes = len(line.encode("utf-8"))
        if line_bytes > max_bytes:
            if current_chunk:
                chunks.append("".join(current_chunk))
                current_chunk = []
                current_bytes = 0
            sub_chars = []
            sub_bytes = 0
            for char in line:
                c_bytes = len(char.encode("utf-8"))
                if sub_bytes + c_bytes > max_bytes:
                    chunks.append("".join(sub_chars))
                    sub_chars = [char]
                    sub_bytes = c_bytes
                else:
                    sub_chars.append(char)
                    sub_bytes += c_bytes
            if sub_chars:
                chunks.append("".join(sub_chars))
        elif current_bytes + line_bytes > max_bytes:
            chunks.append("".join(current_chunk))
            current_chunk = [line]
            current_bytes = line_bytes
        else:
            current_chunk.append(line)
            current_bytes += line_bytes
    if current_chunk:
        chunks.append("".join(current_chunk))
    return chunks


def select_raw_delimiter(fragments: list[str]) -> str:
    used_delimiters = {
        match.group(1)
        for fragment in fragments
        for match in RAW_DELIMITER_OCCURRENCE.finditer(fragment)
        if len(match.group(1)) <= MAX_RAW_DELIMITER_LENGTH
    }

    max_suffix = 10 ** (MAX_RAW_DELIMITER_LENGTH - len("kasumi") - 1) - 1
    for index in range(min(len(used_delimiters) + 1, max_suffix + 1)):
        delimiter = "kasumi" if index == 0 else f"kasumi_{index}"
        if delimiter not in used_delimiters:
            return delimiter

    raise ValueError(
        f"Could not find a safe raw-string delimiter within "
        f"the {MAX_RAW_DELIMITER_LENGTH}-character C++ limit"
    )


def render_fragment(fragment: str, delimiter: str) -> str:
    parts = fragment.split("\r")
    literals = []
    for index, part in enumerate(parts):
        if part:
            literals.append(f'R"{delimiter}({part}){delimiter}"')
        if index < len(parts) - 1:
            literals.append(r'"\r"')
    return " ".join(literals)


def generate_header(en_path: Path, pt_path: Path, out_path: Path) -> None:
    en_text = en_path.read_bytes().decode("utf-8")
    pt_text = pt_path.read_bytes().decode("utf-8")

    en_chunks = chunk_by_bytes(en_text, 2048)
    pt_chunks = chunk_by_bytes(pt_text, 2048)
    delimiter = select_raw_delimiter(en_chunks + pt_chunks)

    lines = [
        "// Generated by scripts/generate_i18n_embedded.py - DO NOT EDIT",
        "#ifndef KASUMI_CLI_I18N_EMBEDDED_HPP",
        "#define KASUMI_CLI_I18N_EMBEDDED_HPP",
        "",
        "#include <span>",
        "#include <string>",
        "#include <string_view>",
        "",
        "namespace kasumi::cli::i18n::embedded {",
        "",
        "inline constexpr std::size_t MAX_FRAGMENT_SIZE = 2048;",
        "",
        "inline constexpr std::string_view EN_JSON_FRAGMENTS[] = {",
    ]

    for chunk in en_chunks:
        lines.append(f"    {render_fragment(chunk, delimiter)},")

    lines.extend([
        "};",
        "",
        "inline constexpr std::string_view PT_BR_JSON_FRAGMENTS[] = {",
    ])

    for chunk in pt_chunks:
        lines.append(f"    {render_fragment(chunk, delimiter)},")

    lines.extend([
        "};",
        "",
        "inline std::string reconstruct(std::span<const std::string_view> fragments) {",
        "    std::size_t total_size = 0;",
        "    for (const auto& fragment : fragments) {",
        "        total_size += fragment.size();",
        "    }",
        "    std::string result;",
        "    result.reserve(total_size);",
        "    for (const auto& fragment : fragments) {",
        "        result.append(fragment);",
        "    }",
        "    return result;",
        "}",
        "",
        "inline std::string reconstructed_en_json() {",
        "    return reconstruct(EN_JSON_FRAGMENTS);",
        "}",
        "",
        "inline std::string reconstructed_pt_br_json() {",
        "    return reconstruct(PT_BR_JSON_FRAGMENTS);",
        "}",
        "",
        "} // namespace kasumi::cli::i18n::embedded",
        "",
        "#endif // KASUMI_CLI_I18N_EMBEDDED_HPP",
        "",
    ])

    content = "\n".join(lines).encode("utf-8")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if out_path.exists():
        if out_path.read_bytes() == content:
            return

    out_path.write_bytes(content)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate embedded i18n catalogs.")
    parser.add_argument("--en", required=True, type=Path, help="Path to en.json")
    parser.add_argument("--pt", required=True, type=Path, help="Path to pt-BR.json")
    parser.add_argument("--output", required=True, type=Path, help="Output header path")
    args = parser.parse_args()

    try:
        generate_header(args.en, args.pt, args.output)
    except ValueError as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    sys.exit(main())
